"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import LayoutResponsiveAppBar from "./components/layoutAppBar";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { Box, Container, Grid, Paper } from '@mui/material';
import * as React from 'react';
import {ColorModeProvider} from "./context/colorModeContext";
import SimpleBottomNavigation from "./components/bottomNavigation";
import NestedList from "./components/nestedSidelList";
import { styled } from '@mui/material/styles';
import theme from "./theme";

const inter = Inter({ subsets: ["latin"] });




// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


const Item = styled(Paper)(({ theme:Theme }) => ({
  backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
  ...theme.typography.body2,
  padding: theme.spacing(1),
  textAlign: 'center',
  color: theme.palette.text.secondary,
}));


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">

      <body 
      className={inter.className}>
      <AppRouterCacheProvider
       options={{ key: 'css' }}
       
       >
    <ColorModeProvider>
      <LayoutResponsiveAppBar/>
      <Container maxWidth="lg" >
      <Grid id='baba' spacing={3} container>
        <Grid item   xs={4}>
        <NestedList/>
        </Grid>
        <Grid item xs={8} >
        {children}
        </Grid>
      </Grid>

        </Container>
        <SimpleBottomNavigation/>
        </ColorModeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
